# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  maven-central:
    type: maven-repository
    url: https://repo.maven.apache.org/maven2/
  jboss-public-repository-group:
    type: maven-repository
    url: https://repository.jboss.org/nexus/content/groups/public/
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      fasterxml-dependencies:
        patterns:
          - "com.fasterxml*"
      netty-vertx-dependencies:
        patterns:
          - "io.netty*"
          - "io.vertx*"
    ignore:
      - dependency-name: 'jakarta.annotation:jakarta.annotation-api'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'jakarta.batch:jakarta.batch-api'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'jakarta.enterprise:jakarta.enterprise.cdi-api'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'jakarta.inject:jakarta.inject-api'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'jakarta.persistence:jakarta.persistence-api'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'jakarta.servlet:jakarta.servlet-api'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'jakarta.transaction:jakarta.transaction-api'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'jakarta.xml.bind:jakarta.xml.bind-api'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'org.jboss.weld*'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
        # Derby 10.16 is the latest version to support Java 17
      - dependency-name: 'org.apache.derby*'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
    open-pull-requests-limit: 10
    registries:
      - maven-central
      - jboss-public-repository-group
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
