# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: JBeret Main Branch Build

on:
  pull_request:
    branches:
      - main
  push:
    branches: [ main ]
  workflow_dispatch:

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  MVN_CMD: './mvnw -V -B -ntp'

jobs:
  build-test-matrix:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-ci') }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v7
      - name: Set up JDKs
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          cache: 'maven'
          java-version: |
            17
            21
            26
            25
      - name: Build and Test on ${{ matrix.os }} - Java 25
        run: ${{ env.MVN_CMD }} clean install
      - name: Build and Test on ${{ matrix.os }} - Java 26
        run: ${{ env.MVN_CMD }} verify '-Dtest.java.home=${{env.JAVA_HOME_26_X64}}${{env.JAVA_HOME_26_ARM64}}' '-Dtest.report.dir=java26'
      - name: Build and Test on ${{ matrix.os }} - Java 21
        run: ${{ env.MVN_CMD }} verify '-Dtest.java.home=${{env.JAVA_HOME_21_X64}}${{env.JAVA_HOME_21_ARM64}}' '-Dtest.report.dir=java21' '-P-java25-test-classpath'
      - name: Build and Test on ${{ matrix.os }} - Java 17
        run: ${{ env.MVN_CMD }} verify '-Dtest.java.home=${{env.JAVA_HOME_17_X64}}${{env.JAVA_HOME_17_ARM64}}' '-Dtest.report.dir=java17' '-P-java25-test-classpath'
      - name: Upload test logs for failed run
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: test-reports-${{ matrix.os }}
          path: |
            **/*.log
            **/surefire-reports/**
            **/failsafe-reports/**

  build-test-wildfly-matrix:
    name: Test WildFly Integration-${{ matrix.os }}${{ matrix.profile }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-ci') }}
    env:
      MVN_CMD: './mvnw -V -B -ntp -am -pl jberet-manifest,test-deployment'
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        profile: ['', '-Pee10', '-Ppreview']
    steps:
      - uses: actions/checkout@v7
      - name: Set up JDKs
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          cache: 'maven'
          java-version: |
            17
            21
            26
            25
      - name: Build and Test on ${{ matrix.os }} - Java 25
        run: ${{ env.MVN_CMD }} clean install ${{ matrix.profile }}
      - name: Build and Test on ${{ matrix.os }} - Java 26
        run: ${{ env.MVN_CMD }} verify '-Dtest.java.home=${{env.JAVA_HOME_26_X64}}${{env.JAVA_HOME_26_ARM64}}' '-Dtest.report.dir=java26' ${{ matrix.profile }}
      - name: Build and Test on ${{ matrix.os }} - Java 21
        run: ${{ env.MVN_CMD }} verify '-Dtest.java.home=${{env.JAVA_HOME_21_X64}}${{env.JAVA_HOME_21_ARM64}}' '-Dtest.report.dir=java21' ${{ matrix.profile }} '-P-java25-test-classpath'
      - name: Build and Test on ${{ matrix.os }} - Java 17
        run: ${{ env.MVN_CMD }} verify '-Dtest.java.home=${{env.JAVA_HOME_17_X64}}${{env.JAVA_HOME_17_ARM64}}' '-Dtest.report.dir=java17' ${{ matrix.profile }} '-P-java25-test-classpath'
      - name: Upload test logs for failed run
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: test-reports-${{ matrix.os }}${{matrix.profile}}
          path: |
            **/*.log
            **/surefire-reports/**
            **/failsafe-reports/**

  build-test-wildfly-secmgr-matrix:
    name: Test WildFly Security Manager Integration-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-ci') }}
    env:
      MVN_CMD: './mvnw -V -B -ntp -am -pl jberet-manifest,test-deployment'
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v7
      - name: Set up JDKs
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          cache: 'maven'
          java-version: |
            17
            21
      - name: Build and Test on ${{ matrix.os }} - Java 21
        run: ${{ env.MVN_CMD }} clean install '-Dsecurity.manager'
      - name: Build and Test on ${{ matrix.os }} - Java 17
        run: ${{ env.MVN_CMD }} verify '-Dtest.java.home=${{env.JAVA_HOME_17_X64}}${{env.JAVA_HOME_17_ARM64}}' '-Dtest.report.dir=java17' '-Dsecurity.manager'
      - name: Upload test logs for failed run
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: test-reports-${{ matrix.os }}
          path: |
            **/*.log
            **/surefire-reports/**
            **/failsafe-reports/**
